In [1]:
import tensorflow as tf

# tf.clip_by_value

In [3]:
v = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

with tf.Session() as sess:
    print(tf.clip_by_value(v, 2.5, 4.5).eval())

[[2.5 2.5 3. ]
 [4.  4.5 4.5]]


通過 `tf.clip_by_value` 可以將一個章輛中的數值限制在一個範圍之內，這樣可以避免一些運算錯誤(比如 $log0$ 是無效的)
從以上範例中可以看到，小於 2.5 的樹都被換成了 2.5，而大於 4.5的數都被換成了 4.5。

# dot product & product

在 TensorFlow 中，兩個矩陣透過 $*$ 相乘，這個操錯不是矩陣乘法，而是元素之間直接相乘。

矩陣乘法需要使用 `tf.matmul` 來完成。

In [4]:
v1 = tf.constant([[1.0, 2.0], [3.0, 4.0]])
v2 = tf.constant([[5.0, 6.0], [7.0, 8.0]])

with tf.Session() as sess:
    print(sess.run(v1*v2))
    
    print(sess.run(tf.matmul(v1, v2)))

[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]


In [11]:
y_ = tf.constant([1.0, 0.0, 0.0])
y1 = tf.constant([0.5, 0.4, 0.1])
y2 = tf.constant([0.8, 0.1, 0.1])

cross_entropy1 = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y1, 1e-10, 1.0)))
cross_entropy2 = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y2, 1e-10, 1.0)))

with tf.Session() as sess:
    print(sess.run(cross_entropy1))
    print(sess.run(cross_entropy2))

0.23104906
0.07438118
